### ISSUE TITLE
Conan 1 is legacy and on a deprecation path. Please upgrade to Conan 2.

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/ssht#77]
Same as https://github.com/astro-informatics/s2let/issues/55

**Comment by jasonmcewen** [comment]
Seem like this issue has been resolved?  See here: https://github.com/astro-informatics/ssht/pull/71#issuecomment-2397834018

**Comment by paddyroddy** [comment]
Yep, looks like it

```
/tmp via 🐍 v3.12.7 (tmp) took 7s
󰂃 8% ❯ cd /tmp; \rm -rf .venv; uv venv; source .venv/bin/activate
Using CPython 3.12.7
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate

/tmp via 🐍 v3.12.7 (tmp)
󰂃 8% ❯ uv pip install ssht
Resolved 7 packages in 1.37s
   Built mysql-connector==2.2.9
Prepared 3 packages in 610ms
Installed 7 packages in 11ms
 + certifi==2024.12.14
 + charset-normalizer==3.4.0
 + idna==3.10
 + mysql-connector==2.2.9
 + requests==2.32.3
 + ssht==2.0.0
 + urllib3==2.3.0
```

**Comment by paddyroddy** [comment]
This is still failing when installing from `pip` @mdavezac, e.g. https://github.com/astro-informatics/sleplet/actions/runs/14185446009/job/39739812070?pr=443. `s2let` appears to be okay (ref: https://github.com/astro-informatics/s2let/issues/55). Does a release need to be made? `sleplet` is very broken at the moment 😢 https://github.com/astro-informatics/sleplet/pulls

<details><summary>Logs in full</summary>
2025-04-01T02:02:07.6466861Z Building wheels for collected packages: sleplet, pyssht
2025-04-01T02:02:07.6475765Z   Building editable for sleplet (pyproject.toml): started
2025-04-01T02:02:08.0090170Z   Building editable for sleplet (pyproject.toml): finished with status 'done'
2025-04-01T02:02:08.0095919Z   Created wheel for sleplet: filename=sleplet-0.1.dev1-0.editable-py3-none-any.whl size=6231 sha256=42cda4d2ff979e7f436a36b1221712cdb5ee6c582197bb7d3aa30d0e644ce160
2025-04-01T02:02:08.0098049Z   Stored in directory: /tmp/pip-ephem-wheel-cache-uikbsr37/wheels/d6/7d/89/f6bda4328f607f51f74b496befa29d8657b4bb26133db34363
2025-04-01T02:02:08.0130106Z   Building wheel for pyssht (pyproject.toml): started
2025-04-01T02:02:11.6975942Z   Building wheel for pyssht (pyproject.toml): finished with status 'error'
2025-04-01T02:02:11.7070156Z   error: subprocess-exited-with-error
2025-04-01T02:02:11.7070642Z   
2025-04-01T02:02:11.7071447Z   × Building wheel for pyssht (pyproject.toml) did not run successfully.
2025-04-01T02:02:11.7072150Z   │ exit code: 1
2025-04-01T02:02:11.7072579Z   ╰─> [164 lines of output]
2025-04-01T02:02:11.7072926Z       
2025-04-01T02:02:11.7073227Z       
2025-04-01T02:02:11.7073668Z       --------------------------------------------------------------------------------
2025-04-01T02:02:11.7074289Z       -- Trying 'Ninja' generator
2025-04-01T02:02:11.7074737Z       --------------------------------
2025-04-01T02:02:11.7075202Z       ---------------------------
2025-04-01T02:02:11.7075608Z       ----------------------
2025-04-01T02:02:11.7076334Z       -----------------
2025-04-01T02:02:11.7076703Z       ------------
2025-04-01T02:02:11.7077036Z       -------
2025-04-01T02:02:11.7077362Z       --
2025-04-01T02:02:11.7078094Z       CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
2025-04-01T02:02:11.7078959Z         Compatibility with CMake < 3.10 will be removed from a future version of
2025-04-01T02:02:11.7079713Z         CMake.
2025-04-01T02:02:11.7080031Z       
2025-04-01T02:02:11.7080435Z         Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
2025-04-01T02:02:11.7081009Z         to tell CMake that the project requires at least <min> but has been updated
2025-04-01T02:02:11.7081746Z         to work with policies introduced by <max> or earlier.
2025-04-01T02:02:11.7082266Z       
2025-04-01T02:02:11.7082717Z       Not searching for unused variables given on the command line.
2025-04-01T02:02:11.7083291Z       
2025-04-01T02:02:11.7083679Z       -- The C compiler identification is GNU 13.3.0
2025-04-01T02:02:11.7084218Z       -- Detecting C compiler ABI info
2025-04-01T02:02:11.7084673Z       -- Detecting C compiler ABI info - done
2025-04-01T02:02:11.7085051Z       -- Check for working C compiler: /usr/bin/cc - skipped
2025-04-01T02:02:11.7085431Z       -- Detecting C compile features
2025-04-01T02:02:11.7085750Z       -- Detecting C compile features - done
2025-04-01T02:02:11.7086259Z       -- Configuring done (0.2s)
2025-04-01T02:02:11.7086549Z       -- Generating done (0.0s)
2025-04-01T02:02:11.7087184Z       -- Build files have been written to: /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/_cmake_test_compile/build
2025-04-01T02:02:11.7087817Z       --
2025-04-01T02:02:11.7088217Z       -------
2025-04-01T02:02:11.7088396Z       ------------
2025-04-01T02:02:11.7088582Z       -----------------
2025-04-01T02:02:11.7088783Z       ----------------------
2025-04-01T02:02:11.7088994Z       ---------------------------
2025-04-01T02:02:11.7089240Z       --------------------------------
2025-04-01T02:02:11.7116436Z       -- Trying 'Ninja' generator - success
2025-04-01T02:02:11.7116842Z       --------------------------------------------------------------------------------
2025-04-01T02:02:11.7117157Z       
2025-04-01T02:02:11.7117357Z       Configuring Project
2025-04-01T02:02:11.7117594Z         Working directory:
2025-04-01T02:02:11.7118337Z           /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/_skbuild/linux-x86_64-3.12/cmake-build
2025-04-01T02:02:11.7118816Z         Command:
2025-04-01T02:02:11.7124471Z           /tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/cmake/data/bin/cmake /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/_skbuild/linux-x86_64-3.12/cmake-install -DPYTHON_VERSION_STRING:STRING=3.12.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPYTHON_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPYTHON_LIBRARY:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/lib/libpython3.12.so -DPython_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPython_ROOT_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPython3_ROOT_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja -DBUILD_TESTING:BOOL=OFF -Dconan_deps=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE:STRING=Release
2025-04-01T02:02:11.7130399Z       
2025-04-01T02:02:11.7130663Z       Not searching for unused variables given on the command line.
2025-04-01T02:02:11.7131027Z       -- The C compiler identification is GNU 13.3.0
2025-04-01T02:02:11.7131331Z       -- Detecting C compiler ABI info
2025-04-01T02:02:11.7131605Z       -- Detecting C compiler ABI info - done
2025-04-01T02:02:11.7131916Z       -- Check for working C compiler: /usr/bin/cc - skipped
2025-04-01T02:02:11.7132225Z       -- Detecting C compile features
2025-04-01T02:02:11.7132492Z       -- Detecting C compile features - done
2025-04-01T02:02:11.7132988Z       -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
2025-04-01T02:02:11.7133362Z       -- Conan: checking conan executable
2025-04-01T02:02:11.7133715Z       -- Conan: Found program /tmp/pip-build-env-fswuo_68/overlay/bin/conan
2025-04-01T02:02:11.7134088Z       -- Conan: Version found Conan version 1.66.0
2025-04-01T02:02:11.7134369Z       
2025-04-01T02:02:11.7135529Z       -- Conan executing: /tmp/pip-build-env-fswuo_68/overlay/bin/conan install /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/conanfile.txt --remote conancenter --generator cmake_find_package --generator cmake_paths --build missing --settings build_type=Release --settings compiler=gcc --settings compiler.version=13
2025-04-01T02:02:11.7136852Z       
2025-04-01T02:02:11.7137086Z       WARN: **************************************************
2025-04-01T02:02:11.7137413Z       WARN: *** Conan 1 is legacy and on a deprecation path **
2025-04-01T02:02:11.7137727Z       WARN: *********** Please upgrade to Conan 2 ************
2025-04-01T02:02:11.7138210Z       WARN: **************************************************
2025-04-01T02:02:11.7138668Z       Auto detecting your dev setup to initialize the default profile (/home/runner/.conan/profiles/default)
2025-04-01T02:02:11.7139106Z       CC and CXX: /usr/bin/cc, None
2025-04-01T02:02:11.7139404Z       ERROR: Not able to automatically detect '/usr/bin/cc' version
2025-04-01T02:02:11.7139749Z       No compiler was detected (one may not be needed)
2025-04-01T02:02:11.7140029Z       Default settings
2025-04-01T02:02:11.7140220Z           os=Linux
2025-04-01T02:02:11.7140418Z           os_build=Linux
2025-04-01T02:02:11.7140628Z           arch=x86_64
2025-04-01T02:02:11.7140827Z           arch_build=x86_64
2025-04-01T02:02:11.7141049Z           build_type=Release
2025-04-01T02:02:11.7141347Z       *** You can change them in /home/runner/.conan/profiles/default ***
2025-04-01T02:02:11.7141702Z       *** Or override with -s compiler='other' -s ...s***
2025-04-01T02:02:11.7141970Z       
2025-04-01T02:02:11.7142134Z       
2025-04-01T02:02:11.7142468Z       WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
2025-04-01T02:02:11.7142881Z       Configuration:
2025-04-01T02:02:11.7143087Z       [settings]
2025-04-01T02:02:11.7143272Z       arch=x86_64
2025-04-01T02:02:11.7143464Z       arch_build=x86_64
2025-04-01T02:02:11.7143675Z       build_type=Release
2025-04-01T02:02:11.7143873Z       compiler=gcc
2025-04-01T02:02:11.7144077Z       compiler.version=13
2025-04-01T02:02:11.7144284Z       os=Linux
2025-04-01T02:02:11.7144463Z       os_build=Linux
2025-04-01T02:02:11.7144643Z       [options]
2025-04-01T02:02:11.7144830Z       [build_requires]
2025-04-01T02:02:11.7145022Z       [env]
2025-04-01T02:02:11.7145190Z       
2025-04-01T02:02:11.7145402Z       fftw/3.3.10: Retrieving from server 'conancenter'
2025-04-01T02:02:11.7145698Z       fftw/3.3.10: Trying with 'conancenter'...
2025-04-01T02:02:11.7145971Z       Downloading conanmanifest.txt
2025-04-01T02:02:11.7146253Z       Downloading conanfile.py
2025-04-01T02:02:11.7146488Z       Downloading conan_export.tgz
2025-04-01T02:02:11.7146882Z       fftw/3.3.10: Downloaded recipe revision 0
2025-04-01T02:02:11.7147530Z       fftw/3.3.10: WARN: precision options is deprecated! use dedicated options 'precision_single', 'precision_double', 'precision_longdouble' and 'precision_quad' instead
2025-04-01T02:02:11.7148251Z       Version ranges solved
2025-04-01T02:02:11.7148504Z           fftw/* versions found in 'conancenter' remote
2025-04-01T02:02:11.7148944Z           Version range '>=3.3' required by 'conanfile.txt' resolved to 'fftw/3.3.10' in remote 'conancenter'
2025-04-01T02:02:11.7149356Z       
2025-04-01T02:02:11.7149545Z       conanfile.txt: Installing package
2025-04-01T02:02:11.7149783Z       Requirements
2025-04-01T02:02:11.7150005Z           fftw/3.3.10 from 'conancenter' - Downloaded
2025-04-01T02:02:11.7150269Z       Packages
2025-04-01T02:02:11.7150523Z           fftw/3.3.10:76fb618e9f590ad1830f3b3f412b2dc9af0b6433 - Build
2025-04-01T02:02:11.7150822Z       
2025-04-01T02:02:11.7151025Z       Installing (downloading, building) binaries...
2025-04-01T02:02:11.7151437Z       fftw/3.3.10: Configuring sources in /home/runner/.conan/data/fftw/3.3.10/_/_/source/src
2025-04-01T02:02:11.7151813Z       fftw/3.3.10:
2025-04-01T02:02:11.7152026Z       fftw/3.3.10: Copying sources to build folder
2025-04-01T02:02:11.7152536Z       fftw/3.3.10: Building your package in /home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433
2025-04-01T02:02:11.7153065Z       fftw/3.3.10: Generator txt created conanbuildinfo.txt
2025-04-01T02:02:11.7153483Z       fftw/3.3.10: Calling generate()
2025-04-01T02:02:11.7154125Z       fftw/3.3.10: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
2025-04-01T02:02:11.7154959Z       fftw/3.3.10: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
2025-04-01T02:02:11.7156364Z       fftw/3.3.10: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
2025-04-01T02:02:11.7157570Z       fftw/3.3.10: Aggregating env generators
2025-04-01T02:02:11.7157831Z       fftw/3.3.10: Calling build()
2025-04-01T02:02:11.7158255Z       fftw/3.3.10: apply_conandata_patches(): No patches defined in conandata
2025-04-01T02:02:11.7160186Z       fftw/3.3.10: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/runner/.conan/data/fftw/3.3.10/_/_/package/76fb618e9f590ad1830f3b3f412b2dc9af0b6433" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" -DENABLE_FLOAT="ON" -DENABLE_LONG_DOUBLE="OFF" -DENABLE_QUAD_PRECISION="OFF" "/home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/src"
2025-04-01T02:02:11.7162068Z       CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
2025-04-01T02:02:11.7162444Z         Compatibility with CMake < 3.5 has been removed from CMake.
2025-04-01T02:02:11.7162746Z       
2025-04-01T02:02:11.7163014Z         Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
2025-04-01T02:02:11.7163467Z         to tell CMake that the project requires at least <min> but has been updated
2025-04-01T02:02:11.7163852Z         to work with policies introduced by <max> or earlier.
2025-04-01T02:02:11.7164125Z       
2025-04-01T02:02:11.7164374Z         Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
2025-04-01T02:02:11.7164692Z       
2025-04-01T02:02:11.7164843Z       
2025-04-01T02:02:11.7165042Z       -- Configuring incomplete, errors occurred!
2025-04-01T02:02:11.7165305Z       fftw/3.3.10:
2025-04-01T02:02:11.7165765Z       fftw/3.3.10: ERROR: Package '76fb618e9f590ad1830f3b3f412b2dc9af0b6433' build failed
2025-04-01T02:02:11.7166414Z       fftw/3.3.10: WARN: Build folder /home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/build/Release
2025-04-01T02:02:11.7166964Z       ERROR: fftw/3.3.10: Error in build() method, line 111
2025-04-01T02:02:11.7167276Z           cmake.configure(variables=variables)
2025-04-01T02:02:11.7169540Z           ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/runner/.conan/data/fftw/3.3.10/_/_/package/76fb618e9f590ad1830f3b3f412b2dc9af0b6433" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" -DENABLE_FLOAT="ON" -DENABLE_LONG_DOUBLE="OFF" -DENABLE_QUAD_PRECISION="OFF" "/home/runner/.conan/data/fftw/3.3.10/_/_/build/76fb618e9f590ad1830f3b3f412b2dc9af0b6433/src"
2025-04-01T02:02:11.7171560Z       CMake Error at _skbuild/linux-x86_64-3.12/cmake-build/conan.cmake:631 (message):
2025-04-01T02:02:11.7171941Z         Conan install failed='1'
2025-04-01T02:02:11.7172191Z       Call Stack (most recent call first):
2025-04-01T02:02:11.7172511Z         cmake/conan_dependencies.cmake:12 (conan_cmake_install)
2025-04-01T02:02:11.7172826Z         CMakeLists.txt:17 (include)
2025-04-01T02:02:11.7173188Z       
2025-04-01T02:02:11.7173350Z       
2025-04-01T02:02:11.7173561Z       -- Configuring incomplete, errors occurred!
2025-04-01T02:02:11.7173850Z       Traceback (most recent call last):
2025-04-01T02:02:11.7178641Z         File "/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 660, in setup
2025-04-01T02:02:11.7179228Z           env = cmkr.configure(
2025-04-01T02:02:11.7179472Z                 ^^^^^^^^^^^^^^^
2025-04-01T02:02:11.7180019Z         File "/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 354, in configure
2025-04-01T02:02:11.7180544Z           raise SKBuildError(msg)
2025-04-01T02:02:11.7180778Z       
2025-04-01T02:02:11.7180998Z       An error occurred while configuring with CMake.
2025-04-01T02:02:11.7181276Z         Command:
2025-04-01T02:02:11.7186770Z           /tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/cmake/data/bin/cmake /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/_skbuild/linux-x86_64-3.12/cmake-install -DPYTHON_VERSION_STRING:STRING=3.12.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPYTHON_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPYTHON_LIBRARY:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/lib/libpython3.12.so -DPython_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPython_ROOT_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/bin/python -DPython3_ROOT_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/hostedtoolcache/Python/3.12.9/x64/include/python3.12 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-fswuo_68/overlay/lib/python3.12/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja -DBUILD_TESTING:BOOL=OFF -Dconan_deps=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE:STRING=Release
2025-04-01T02:02:11.7192591Z         Source directory:
2025-04-01T02:02:11.7193075Z           /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490
2025-04-01T02:02:11.7193431Z         Working directory:
2025-04-01T02:02:11.7193868Z           /tmp/pip-install-d7652od2/pyssht_38c7066f3ebf4bca9e5a21be130ee490/_skbuild/linux-x86_64-3.12/cmake-build
2025-04-01T02:02:11.7194369Z       Please see CMake's output for more information.
2025-04-01T02:02:11.7194645Z       
2025-04-01T02:02:11.7194822Z       [end of output]
2025-04-01T02:02:11.7195015Z   
2025-04-01T02:02:11.7195326Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2025-04-01T02:02:11.7195729Z   ERROR: Failed building wheel for pyssht
2025-04-01T02:02:11.7196004Z Successfully built sleplet
2025-04-01T02:02:11.7196231Z Failed to build pyssht
2025-04-01T02:02:11.8109608Z ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyssht)
2025-04-01T02:02:12.2376657Z ##[error]Process completed with exit code 1.
2025-04-01T02:02:12.2477448Z Post job cleanup.
2025-04-01T02:02:12.2541944Z Post job cleanup.
2025-04-01T02:02:12.3466256Z [command]/usr/bin/git version
2025-04-01T02:02:12.3507622Z git version 2.49.0
2025-04-01T02:02:12.3550257Z Temporarily overriding HOME='/home/runner/work/_temp/b2a34343-5253-408a-92f5-3f6703df5149' before making global git config changes
2025-04-01T02:02:12.3551589Z Adding repository directory to the temporary git global config as a safe directory
2025-04-01T02:02:12.3556445Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/sleplet/sleplet
2025-04-01T02:02:12.3590838Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2025-04-01T02:02:12.3623272Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2025-04-01T02:02:12.3853667Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2025-04-01T02:02:12.3874686Z http.https://github.com/.extraheader
2025-04-01T02:02:12.3887792Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2025-04-01T02:02:12.3918875Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2025-04-01T02:02:12.4243881Z Cleaning up orphan processes
</detail>

**Comment by mdavezac** [comment]
Is it really trying to install the newest pyssht? It looks like it's still calling out to Conan 1.

**Comment by paddyroddy** [comment]
> Is it really trying to install the newest pyssht? It looks like it's still calling out to Conan 1.

Sorry I hadn't seen you'd made a release today. I force deleted all GitHub Actions cache and ran CI again, and it looks to be working okay!
